### PR TITLE
Support ElasticSearch 5.x and 6.x

### PR DESCRIPTION
**Pull request by slava-vishnyakov**
Thanks to @ariejan's PR #62 and @5andi5's  [this comment](https://github.com/dokku/dokku-elasticsearch/issues/61#issuecomment-395429548) I managed to achieve compatibility with both ES5 and ES6.

```
# dokku elasticsearch:list
NAME         VERSION                                              STATUS   EXPOSED PORTS  LINKS
es-6.6.0     elasticsearch:6.6.0                                  running  -              -
es-5.6.14    elasticsearch:5.6.14                                 running  -              -
es-6.4.2     elasticsearch:6.4.2                                  running  -              -
es-6.5.4     elasticsearch:6.5.4                                  running  -              -
es-2.3.5     elasticsearch:2.3.5                                  running  -              -
```

This already includes fixes from #62 by @ariejan.

ES5 might start with a few errors in the log if there's less than 2G memory at start, but still starts (ES5 stores configs in two locations, so we need to run `ln -s` in restarting container until ES loads correct JVM option of 512m)

ES6 starts smoothly

This should solve #53.

If you want to try this PR:

```
cd /var/lib/dokku/plugins/enabled/elasticsearch
git checkout -B fix_es6
git remote add sv https://github.com/slava-vishnyakov/dokku-elasticsearch.git
git pull sv es6_fix2

export ELASTICSEARCH_IMAGE_VERSION="6.6.0"
dokku elasticsearch:create lolipop
```

P.S. If this is merged - maybe we should bump ES installed by default  from 2.3.5 to 6.6.0?

A note to myself:

```
echo 'xpack.security.enabled: false' | \
     sudo tee -a /var/lib/dokku/services/elasticsearch/SERVICENAME/config/elasticsearch.yml
```

to avoid license problems spamming the logs. (Replace SERVICENAME with your service name)

### CODE REVIEW

**Comment by pahaz** [comment]
Any comments or news? Is it going to be merged?

I have some problem with `expose`:
```
root@testing /var/lib/dokku/plugins/enabled/elasticsearch # dokku elasticsearch:list
 !     There are no Elasticsearch services
root@testing /var/lib/dokku/plugins/enabled/elasticsearch # dokku elasticsearch:create lolipop01 --image-version 6.5.4 --image elasticsearch
=====> Extracting config files
2a55df86a1ee97654e29f8dc5c4ae914b87c54aba4d59f150e71735f7a020f2d
       Waiting for container to be ready
=====> Elasticsearch container created: lolipop01
=====> Container Information
       Config dir:          /var/lib/dokku/services/elasticsearch/lolipop01/config
       Data dir:            /var/lib/dokku/services/elasticsearch/lolipop01/data
       Dsn:                 http://dokku-elasticsearch-lolipop01:9200
       Exposed ports:       -
       Id:                  f1d36194302f94778bcd402f85dcde6877a76b139e63ad2a6a06d16cb6637414
       Internal ip:         172.17.0.3
       Links:               -
       Service root:        /var/lib/dokku/services/elasticsearch/lolipop01
       Status:              running
       Version:             elasticsearch:6.5.4
root@testing /var/lib/dokku/plugins/enabled/elasticsearch # dokku elasticsearch:expose lolipop01
=====> Starting container
docker: Error response from daemon: Conflict. The container name "/dokku.elasticsearch.lolipop01" is already in use by container f1d36194302f94778bcd402f85dcde6877a76b139e63ad2a6a06d16cb6637414. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
```

**Comment by slava-vishnyakov** [comment]
Strange, expose works for me with the same version:

```
# dokku elasticsearch:create lolipop01 --image-version 6.5.4 --image elasticsearch
=====> Extracting config files
dd4db7894dcc77bc8525cb46291b2f1aaf0f1af33cefe849195324fdd05f97a3
       Waiting for container to be ready
=====> Elasticsearch container created: lolipop01
=====> Container Information
       Config dir:          /var/lib/dokku/services/elasticsearch/lolipop01/config
       Data dir:            /var/lib/dokku/services/elasticsearch/lolipop01/data
       Dsn:                 http://dokku-elasticsearch-lolipop01:9200
       Exposed ports:       -
       Id:                  27e06ede7bfd464a4e3f0909b0b716b2ca8fb79cc4881ee1b55bb46400c34ff3
       Internal ip:         172.17.0.5
       Links:               -
       Service root:        /var/lib/dokku/services/elasticsearch/lolipop01
       Status:              running
       Version:             elasticsearch:6.5.4

# dokku elasticsearch:expose lolipop01
-----> Service lolipop01 exposed on port(s) [container->host]: 9200->19532 9300->10040

# dokku elasticsearch:unexpose lolipop01
-----> Service lolipop01 unexposed
```

**Comment by slava-vishnyakov** [comment]
What does `dokku elasticsearch:list` show before you try to expose? Is the service running?

**Comment by pahaz** [comment]
Yes. It looks like a not this patch problem: https://github.com/dokku/dokku-elasticsearch/issues/65

**Comment by slava-vishnyakov** [comment]
6.6.0 was recently released, works with this PR correctly.

**Comment by eliias** [comment]
Tested and working great for me. Any ETA on this PR? I have had run 6.6.0 on a custom docker-compose setup for a while and I cannot wait to replace this with the backing service in production.

**Comment by templth** [comment]
I tried to test this but got an error:

```
export ELASTICSEARCH_IMAGE_VERSION="6.6.0"
root@host:/var/lib/dokku/plugins/enabled/elasticsearch# dokku elasticsearch:create myindex
=====> Copying config files into place
cp: cannot stat '/etc/elasticsearch/.': No such file or directory
cp: cannot stat '/etc/elasticsearch/.': No such file or directory
```

Perhaps someone had this error... Thanks for your help!

**Comment by josegonzalez** [comment]
I've rebased this onto master. Master now runs _actual_ tests within Dokku, so we should be able to see if this works without me needing to manually verify anything.

**Comment by templth** [comment]
@slava-vishnyakov @josegonzalez I still have the error after having reinstalled the plugin with the latest master version...

**Comment by josegonzalez** [comment]
This did not get merged into master, so yes, you would still have errors.

**Comment by slava-vishnyakov** [comment]
@josegonzalez Thank you for your work on Dokku! It's really great!

**Comment by templth** [comment]
@josegonzalez thanks very much! Will do tests with this...

**Pull request merged**
